<a href="https://colab.research.google.com/github/anishyathinesh/RIT_ML/blob/main/2024_fall/Lectures/ML3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML 3: NumPy and Pandas

In [59]:
import numpy as np #library for work with arrays
import pandas as pd #library for work with tables
import matplotlib.pyplot as plt #library for visualization
#import sys
#import sklearn

In [60]:
#sklearn.__version__

## Numpy
Useful information: https://realpython.com/numpy-tutorial/

In [61]:
np.__version__

'1.26.4'

In [62]:
a = [1, 2, 3]
a = np.array(a)
a #type(a[0])

array([1, 2, 3])

In [63]:
b = a #.copy()
a[1] = 5
print(a)
print(b)

[1 5 3]
[1 5 3]


### Shape

In [64]:
a.shape

(3,)

In [65]:
np.array([a]).shape

(1, 3)

In [66]:
b = a.reshape(1,-1)
#(a.reshape(-1,1)).shape
b.shape

(1, 3)

In [67]:
a.T
#b.T

array([1, 5, 3])

In [68]:
c = np.random.rand(4,3)
c

array([[0.15984493, 0.2223551 , 0.14386084],
       [0.55783764, 0.06632783, 0.8793299 ],
       [0.28936403, 0.94237627, 0.35536901],
       [0.59763337, 0.7303591 , 0.72666283]])

In [69]:
c.reshape(1,-1)

array([[0.15984493, 0.2223551 , 0.14386084, 0.55783764, 0.06632783,
        0.8793299 , 0.28936403, 0.94237627, 0.35536901, 0.59763337,
        0.7303591 , 0.72666283]])

In [70]:
c.max(axis=1)

array([0.2223551 , 0.8793299 , 0.94237627, 0.7303591 ])

### Broadcasting

In [71]:
c+c.max(axis=0)
#c+c.max(axis=1).reshape(-1,1)

array([[0.7574783 , 1.16473137, 1.02319075],
       [1.15547101, 1.0087041 , 1.7586598 ],
       [0.8869974 , 1.88475255, 1.23469891],
       [1.19526673, 1.67273537, 1.60599273]])

### Matrix Multiplication

In [72]:
c*c
#c.dot(c.T)
#np.matmul(c.T,c)

array([[0.0255504 , 0.04944179, 0.02069594],
       [0.31118283, 0.00439938, 0.77322108],
       [0.08373154, 0.88807304, 0.12628713],
       [0.35716564, 0.53342441, 0.52803887]])

### Change type

In [73]:
c.dtype
#c.astype(np.float32)

dtype('float64')

### Problem 1.
Assume that in rows of matrix $A = \begin{pmatrix} x^{(1)}_1 & x^{(1)}_2 & x^{(1)}_3 \\ x^{(2)}_1 & x^{(2)}_2 & x^{(3)}_3\\ \cdots & \cdots & \cdots\\ x^{(20)}_1 & x^{(20)}_2 & x^{(20)}_3 \end{pmatrix}$ we have coordinates of 20 points and in rows of matrix $B = \begin{pmatrix} y^{(1)}_1 & y^{(1)}_2 & y^{(1)}_3 \\ y^{(2)}_1 & y^{(2)}_2 & y^{(3)}_3\\ \cdots & \cdots & \cdots\\ y^{(5)}_1 & y^{(5)}_2 & y^{(5)}_3 \end{pmatrix}$ we have coordinates of 5 other points. Using boadcasting, get a matrix with Eucledean distances from every point $x^{i}$ to every point $y^{(j)}:$
$$
D =  \begin{pmatrix} d(x^{(1)}, y^{(1)}) & d(x^{(1)}, y^{(2)}) & \ldots & d(x^{(1)}, y^{(5)}) \\ d(x^{(2)}, y^{(1)}) & d(x^{(2)}, y^{(2)}) & \ldots & d(x^{(2)}, y^{(5)})\\ \cdots & \cdots & \cdots & \cdots\\ d(x^{(20)}, y^{(1)}) & d(x^{(20)}, y^{(2)}) & \ldots & d(x^{(20)}, y^{(5)}) \end{pmatrix}
$$

In [78]:
A = np.random.randn(20,3)
B = np.random.randn(5,3)

C = A[:, None, :]
D = B[None, :, :]

sq = (C - D) ** 2
add = sq.sum(axis=-1)

ans = np.sqrt(add)

In [79]:
print(A)
print(B)
print(ans)

[[-1.07655664e+00  7.02448545e-01  2.86871829e-01]
 [-1.07748565e+00 -9.05400060e-03 -3.19064674e-01]
 [ 1.25681247e+00  1.57086411e+00  1.62359290e-01]
 [ 2.95995042e-01 -3.65499215e-01 -1.51754672e+00]
 [-2.84949185e-01 -1.85829126e+00  1.06835031e+00]
 [ 3.71013079e-01 -7.40084087e-01 -1.08295896e+00]
 [-3.01512972e-02 -8.20862204e-01 -1.90903527e+00]
 [-4.07063676e-01  1.04641452e+00  8.06098788e-01]
 [ 1.32108722e+00 -4.22624851e-01  4.79201238e-01]
 [ 1.65394315e+00 -8.79418916e-01  1.35892106e+00]
 [ 7.86613627e-01  1.05700950e-01  9.35651084e-01]
 [ 1.14018267e+00 -3.00919635e-01  8.60906597e-01]
 [-9.31195905e-01  3.26396137e-01  4.82759200e-02]
 [ 1.66392503e-01  1.49616573e+00  2.12304528e-03]
 [-1.44064800e-01 -7.69606916e-01 -2.38618096e+00]
 [ 1.51749462e+00  1.74979782e-01 -8.62574868e-01]
 [-6.36791348e-01  2.35754777e-01 -7.17451372e-01]
 [-5.56042094e-03  2.27155218e-01  9.28951043e-01]
 [-8.49763901e-01  1.21249097e+00 -1.35376819e+00]
 [-6.32991789e-01 -8.06302103e-

### Problem 2.
A unit ball centered in the origin (neighborhood of the origing of raduis 1) in $\ell_1$ metric is defined as
$$
\{(x,y)\in\mathbb{R}^2:|x-0|+|y-0|=|x|+|y|<1\}.
$$
To plot the boundary of this ball you can plot the surface $z=|x|+|y|$ and then take its section at the level $z=1$, you'll get the level curve
$$
|x|+|y|=1.
$$
The unit ball in $\ell_2$ metric is plotted below, plot a unit ball in $\ell_1$ metric (you can modify the existing code).

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
def f(x, y):
    return np.sqrt(x**2 + y**2)

In [ ]:
x = np.linspace(-2, 2, 400)
y = np.linspace(-2, 2, 400)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

In [ ]:
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
surf = ax.plot_surface(X, Y, Z, cmap='viridis', edgecolor='none')

# Add a color bar which maps values to colors
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=5)

# Add labels
ax.set_title('$f(x,y) = \sqrt{x^2 + y^2}$')
ax.set_xlabel('$x$')
ax.set_ylabel('$y$')
ax.set_zlabel('$f(x,y)$')

# Show the plot
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))

# Plot the function as a filled contour plot
contour = plt.contourf(X, Y, Z, levels=50, cmap='viridis')
plt.colorbar(contour, label='$f(x,y)$')

# Plot the level curve f(x,y) = 1
plt.contour(X, Y, Z, levels=[1], colors='red', linewidths=2)

# Add labels and title
plt.title('$f(x,y) = \sqrt{x^2 + y^2}$ and the level curve $f(x,y) = 1$')
plt.xlabel('$x$')
plt.ylabel('$y$')

# Show the plot
plt.grid(True)
plt.axis('equal')
plt.show()

## Pandas
### Download data
* .csv (Comma Separated Files) [pandas.read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)
* .xls (eXceL Spreadsheet) [pandas.read_excel()](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)
* .json (JavaScript Object Notation) [pandas.read_json()](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)
* .txt

Save .csv file from https://www.randomservices.org/random/data/Galton.html

Another source: https://raw.githubusercontent.com/data-8/materials-fa17/master/lec/galton.csv

F. Galton introduced the term _regression._ In the figure below you can see that "extremely tall parents tend to have children who are taller than average and extremely small parents tend to have children who are smaller than average, but in both cases the children tend to be closer to the average than were their parents". (Stephen Senn _Francis Galton and regression to the mean._ Significance, Vol. 8, Iss. 3)

![title](https://upload.wikimedia.org/wikipedia/commons/b/b2/Galton%27s_correlation_diagram_1875.jpg)
**Francis Galton.** *Regression towards mediocrity in hereditary stature.* The Journal of the Anthropological Institute of Great Britain and Ireland. 15: 246–263 (1886)

In [ ]:
#To see the current directory, you can type
!pwd

In [ ]:
!ls

In [ ]:
#PATH = 'Galtons Height Data.csv'

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anton-selitskiy/The-Art-of-ML/main/Galtons%20Height%20Data.csv')

In [ ]:
df.head() #df.tail(6)

In [ ]:
df.info()

In [ ]:
df.describe()

### Dictionary and creation of dataframes

In [ ]:
d = {'c1': [0, 1], 'c2':[3, 4]}

In [ ]:
d['c1']

In [ ]:
df1 = pd.DataFrame(data = d)
df1.head()

### Access to Columns

In [ ]:
df.columns #.values

In [ ]:
for i in df.columns:
    print(i)

In [ ]:
df.columns[0]

In [ ]:
d = dict(zip(df.columns.values[[0,1,2,4,5]], [np.int32, np.float32, np.float32, np.float32, np.int32]))

In [ ]:
#df2 = pd.read_csv(PATH, dtype=d)
#df2.info()

### Access to Rows

In [ ]:
df.index

### Access by index

In [ ]:
df.iloc[df.index % 2 == 0].head(5)
#df.iloc[1,2]

In [80]:
df.head()

Family  Father  Mother Gender  Height  Kids  Sex
0       1    78.5    67.0      M    73.2     4    0
1       1    78.5    67.0      F    69.2     4    1
2       1    78.5    67.0      F    69.0     4    1
3       1    78.5    67.0      F    69.0     4    1
4       2    75.5    66.5      M    73.5     4    0

from matplotlib import pyplot as plt
_df_0['Family'].plot(kind='hist', bins=20, title='Family')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Father'].plot(kind='hist', bins=20, title='Father')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Mother'].plot(kind='hist', bins=20, title='Mother')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Height'].plot(kind='hist', bins=20, title='Height')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Family', y='Father', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Father', y='Mother', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Mother', y='Height', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='Height', y='Sex', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Family']
  ys = series['Father']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('Family', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='Gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Family')
_ = plt.ylabel('Father')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Family']
  ys = series['Mother']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('Family', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='Gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Family')
_ = plt.ylabel('Mother')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Family']
  ys = series['Height']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('Family', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='Gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Family')
_ = plt.ylabel('Height')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Family']
  ys = series['Sex']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('Family', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='Gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Family')
_ = plt.ylabel('Sex')

from matplotlib import pyplot as plt
_df_13['Family'].plot(kind='line', figsize=(8, 4), title='Family')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Father'].plot(kind='line', figsize=(8, 4), title='Father')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Mother'].plot(kind='line', figsize=(8, 4), title='Mother')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['Height'].plot(kind='line', figsize=(8, 4), title='Height')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='Family', y='Gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='Father', y='Gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='Mother', y='Gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='Height', y='Gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
#df.columns = ['Family', 'Father', 'Mother', 'AverageHeight', 'Kids', 'Num', 'Gender', 'Height']
#df.Gender = df.Gender.map({'male': 'M', 'female': 'F'})

### Visualization

In [ ]:
plt.scatter(df[df['Gender']=='M'].Father, df[df['Gender']=='M'].Height, label="M", alpha=0.5)
plt.scatter(df[df['Gender']=='F'].Father, df[df['Gender']=='F'].Height, label="F", alpha=0.5, c='pink')
plt.xlabel("Father's Height")
plt.ylabel("Child's Height")
plt.legend()
plt.show()

### Working with columns

In [ ]:
plt.scatter(df[df['Gender']=='M'].Father, df[df['Gender']=='M'].Height-df[df['Gender']=='M'].Height.mean(), alpha=0.5)
plt.scatter(df[df['Gender']=='F'].Father, df[df['Gender']=='F'].Height-df[df['Gender']=='F'].Height.mean(), alpha=0.5, c='pink')

### Delete columns

In [ ]:
df.drop("Height", axis=1).head()  #inplace=True

### View elements

In [ ]:
set(df["Gender"])
#df.Gender.unique()

### Change values

In [ ]:
df["Sex"] = df.Gender.map({"M":0, "F":1})
print(df.Sex.dtype)
df.head()

In [ ]:
#df["NewAge"] = df["Age"].apply(lambda x: x+100)

In [ ]:
df.groupby("Gender")["Height"].mean()

In [96]:
df.groupby("Family")["Height"].count().head()

Family
1    4
2    4
3    2
4    5
5    6
Name: Height, dtype: int64

In [92]:

(df.groupby("Family")["Height"].mean() > 70).sum()

19

In [95]:
df[(df.Height > 70) & (df.Gender=="M")].head()

Family  Father  Mother Gender  Height  Kids  Sex
0        1    78.5    67.0      M    73.2     4    0
4        2    75.5    66.5      M    73.5     4    0
5        2    75.5    66.5      M    72.5     4    0
8        3    75.0    64.0      M    71.0     2    0
10       4    75.0    64.0      M    70.5     5    0

## Problems
3. What is the fraction of families with 3 or more children?

In [112]:
(df.groupby("Family")["Kids"].size() >= 3).sum() / df.groupby("Family")["Kids"].size().count()

0.7360406091370558

4. Create a new column with the avarage height of the parents

In [115]:
df['AVG Height'] = df.groupby("Family")["Mother"].mean() + df.groupby("Family")["Father"].mean()

In [117]:
df.head()

Family  Father  Mother Gender  Height  Kids  Sex  AVG Height
0       1    78.5    67.0      M    73.2     4    0         NaN
1       1    78.5    67.0      F    69.2     4    1       70.10
2       1    78.5    67.0      F    69.0     4    1       69.25
3       1    78.5    67.0      F    69.0     4    1       69.50
4       2    75.5    66.5      M    73.5     4    0       66.70

5* (not graded). Plot a scatterplots of male vs the avarage parents' height and females $\times 1.08$ (the guess by Galton) _"which is equivalent to adding a little less than one-twelfthto each female height. It differs a very little from the factors employed by other anthropologists, who, moreover, differ a trifle between themselves; anyhow,  itsuits my data better than 1.07 or 1.09. The final result is not of a kind to be affected by these minute details, for it happened that, owing to a mistaken direction,the computer to whom I first entrusted the figures used a somewhat different factor, yet the result came out closely the same."_ http://www.stat.ucla.edu/~nchristo/statistics100C/history_regression.pdf

In [ ]:
#Your code
#plt.scatter(df[df['Gender']=='M'].Father, df[df['Gender']=='M'].Height, alpha=0.5)
#plt.scatter(df[df['Gender']=='F'].Father, df[df['Gender']=='F'].Height*1.08, alpha=0.5, c='pink')

It's a genius guess by Galton allowed him to use more data for analysis